### ISSUE TITLE
license for Biblia Tysiąclecia

### ISSUE THREAD

**Issue by verdulo** [AndBible/andbible-extra#2]
I have doubts about legality of the document [Biblia Tysiąclecia](https://github.com/AndBible/andbible-extra/blob/master/zip/PolBibTysia.zip).  The section "About" in the document says: 

> Content obtained from Bible Gateway, which notes that this version's text is in the public domain.

and section "DistributionLicense":
>Public domain

However the document is not currently present on the website https://www.biblegateway.com/versions/

The first translation was created in 1965, so it cannot be in the [public domain](https://pl.wikipedia.org/wiki/Domena_publiczna) in Poland. The full text from the year 2003 is available on the website of publisher Pallottinum: https://biblia.deon.pl/. The [license](https://biblia.deon.pl/menu.php?st_id=1) is

>  © All rights reserved. Using requires permission of the publisher Pallottinum in Poznań.

**Comment by tuomas2** [comment]
it is originally from xiphos repo. I can remove it.
